version: '3.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: thanadet63070073/backend-image

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: thanadet63070073/frontend-image
