version: '3.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: thanadet63070073/backend_image

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: thanadet63070073/frontend_image
