version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: thanadet63070073/backend_image:1.0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: thanadet63070073/frontend_image:1.0
